### ISSUE TITLE
Incorrect output of TypeKeys

### ISSUE THREAD

**Issue by cameron707** [pywinauto/pywinauto#124]
I'm trying to automate turning bluetooth on in Windows 8.1 using the latest pywinauto 0.5.4. Unfortunately there's no easy way other than through the start menu. When I send keys to the start menu I always get the first character as a 'd'. Example code: Replace the "a" with anything and it always types it out as a "d".

    from pywinauto import application
    from time import sleep
    
    app = application.Application()
    app.Start("Notepad.exe")
    
    app.Notepad.TypeKeys("{LWIN}")
    sleep(0.01)
    app.Notepad.TypeKeys("a")
    app.Notepad.Close()

**Comment by vasily-v-ryabov** [comment]
Is it Python 2.7 or 3.x?
Did you try Unicode string explicitly? TypeKeys(u"a")

TypeKeys() uses locale.getpreferredencoding() to convert between bytes and Unicode. Which encoding is on your system?

**Comment by vasily-v-ryabov** [comment]
If you need working with start menu only, there might be much simpler:
```python
from pywinauto.SendKeysCtypes import SendKeys

SendKeys(u'{LWIN}any even Russian symbols: бла-бла{ENTER}', with_spaces=True)
```

If you work in 64-bit Windows, you also need a 64-bit Python because explorer.exe is a 64-bit process. And, of course, Administrator privileges are required for Python script to have an access for some system settings like Bluetooth connections. In some cases even UAC should be fully disabled, but it seems not for Bluetooth.

Please check that you tried all these things and let us know whether it works.

P.S. I could find the way to run "Add a device" Bluetooth wizard on Win7 x64:
```python
import pywinauto

app = pywinauto.Application()
app.Start('DevicePairingWizard.exe')

app.Add_a_device.Cancel.Click()
```
Hope it helps.

**Comment by vasily-v-ryabov** [comment]
Closing since no replies during 2 weeks. Please re-open if the problem still exists.
