### ISSUE TITLE
When will uiautomation be supported in pywinauto?

### ISSUE THREAD

**Issue by lanzorg** [pywinauto/pywinauto#136]
I like the pywinauto API for UI automation.
However it lacks essential features for me like automation for metro/modern UI applications.

This project, also written in python, supports much more UI things:
https://github.com/yinkaisheng/Python-UIAutomation-for-Windows

Maybe could you add some code from this project inside pywinauto?

**Comment by vasily-v-ryabov** [comment]
Everyone is waiting for this feature. :)
Issue #3 (WPF support) was requested 5 years ago.

UI Automation API support is planned to release until February, 29 (0.6.0).
We already have some basic prototype in [UIA branch](https://github.com/pywinauto/pywinauto/tree/UIA). But the API is not finalized.

**Comment by lanzorg** [comment]
Will it support latest uiautomation features like UIAComWrapper?
Will the API (app.dialog.control) change?

**Comment by vasily-v-ryabov** [comment]
The API will not change too much. We're just trying to be more PEP-8 complaint. So line `app.Dialog.OK.ClickInput()` will change to `app.Dialog.OK.click_input()`. The old name `ClickInput()` will be supported in 0.6.x for native wrappers, but not in 0.7.0.

UIA wrappers will have PEP-8 complaint method names only.

We use native `UIAutomationClient.dll` so it should work the same way as UIAComWrapper (as far as I understand it should NOT contain .NET specific bugs).

**Comment by vasily-v-ryabov** [comment]
0.6.0 release has been postponed until July, 2016.

**Comment by sragons** [comment]
Hello,
Is v0.6 ready to use ?
I'd to test win.window_(automation_id=321)
Thanks

**Comment by airelil** [comment]
Hi @sragons, the work is still in progress. We just need more contributors in order to finish the planned features. Refer to this [TODO](https://github.com/pywinauto/pywinauto/wiki/TODO) page on our Wiki for more details. You can play with [```UIA```](https://github.com/pywinauto/pywinauto/tree/UIA) branch it's quite stable only lacks wrappers for many controls.

Regarding your question (provided you use [```UIA```](https://github.com/pywinauto/pywinauto/tree/UIA) branch). AFAIK, you can't refer to a top window by ```automation_id``` as the top window doesn't have it. However, you can use filtering by ```automation_id`` to find any children of the window. Check my small example below.
 
```python
from pywinauto import Application

# create Application object with UIA support
app = Application(backend='uia')

# start Notepad
app.start("notepad.exe")

# find a child control with automation_id = 15
# Notice that the parameter is called 'auto_id'
# and the id itself is passed as a string (not int)
ctl = app.UntitledNotepad.child_window(auto_id="15")

# print indentifiers of the found control
ctl.print_control_identifiers()
print(ctl.friendly_class_name())

```

**Comment by sragons** [comment]
Thank you for your answer 
I'd to try to contribute ...

**Comment by sragons** [comment]
Hello,
What is the difference between window_ and child_window methods ?
thank you

**Comment by vasily-v-ryabov** [comment]
Hi @sragons, `window_` is used for top-level windows (it's a method of `Application` objects) while `child_window` is for a control specification inside the subtree (it's a method of `WindowSpecification` object which create another nested `WindowSpecification` object with 2 or more search criteria).

**Comment by vasily-v-ryabov** [comment]
Final release deadline for 0.6.0 is October, 30.
We're going to release all that we have time to finalize. Fixes on the edges will be provided in further updates.

**Comment by sragons** [comment]
Congratulation for the huge work

**Comment by vasily-v-ryabov** [comment]
We're going to publish the release on October, 31 with some last minute improvements for `hooks` module.

**Comment by vasily-v-ryabov** [comment]
Faced with some problems while uploading to TestPyPI. Need some more time to resolve. My apologies.

**Comment by vasily-v-ryabov** [comment]
Now `pip install -U pywinauto` should work. Anyone please check it on your side. I have some strange behavior on py3.4 (32-bit): installer doesn't try to install `pypiwin32` somehow.

**Comment by vasily-v-ryabov** [comment]
0.6.0 is published! Thanks a lot for everyone involved into this interesting marathon.
If you see some issues, please submit it separately. Enjoy!

**Comment by lanzorg** [comment]
Amazing job! Thanks!
