### ISSUE TITLE
click error on itunes

### ISSUE THREAD

**Issue by wangtubs** [pywinauto/pywinauto#333]
python 2.7.13 64x on windows 2008 R2
```
from pywinauto.application import Application
app = Application(backend="uia").connect(path="iTunes.exe")
....
try:
    itunes.Static.Pane0.child_window(title="Continue", found_index=0,visible_only=False).click()
except Exception as e:
    print e

```
ouput:

`{'parent': <uia_element_info.UIAElementInfo - '', iTunesWebViewControl, 31457632>, 'title': 'Continue', 'visible_only': False, 'found_index': 0, 'top_level_only': False, 'backend': u'uia'}`
the error happens quite often. 20-50%

**Comment by airelil** [comment]
Just a small remark: why do you try to click on something that is invisible ? You use ```visible_only=False``` in your filters

**Comment by wangtubs** [comment]
does that matter? I can also remove it.

**Comment by airelil** [comment]
I'm not sure yet, just thinking. If your control is visible you may try to use "click_input" that is a more realistic mouse emulation.

**Comment by vasily-v-ryabov** [comment]
Hi @wangtubs please provide more detailed output and where it happens (which page of iTunes?). So that I could reproduce it on my side.

From your report I can assume it fails with `ElementNotFound` error. Usually such timing issues happen when parent window initialization takes around 5 seconds (default timeout in pywinauto) so you have 50% probability of a failure. To make it stable just use method `.wait('ready', timeout=10)`.
```python
continue = itunes.Static.Pane0.child_window(title="Continue", found_index=0, visible_only=False)
try:
    continue.wait('visible enabled', timeout=10) # wait 10 seconds
    continue.click()
except Exception as e:
    print e
```

**Comment by wangtubs** [comment]
hi, thanks. It seems my problem. I use both lackey and pywinauto. sometimes gets error.
