### ISSUE TITLE
Change item in combobox window form

### ISSUE THREAD

**Issue by woodsongem** [pywinauto/pywinauto#368]
Hi All,

I am new to pywinauto. please share code for change item  in combo-box.

**Comment by vasily-v-ryabov** [comment]
Hi @woodsongem , which backend do you use? It might differ for `"uia"` and `"win32"` param in `Application` object constructor. But generally it looks like the following (taken from tests for WPF, `backend="uia"`):
```python
app.MainWindowTitle.ComboBox.select('Combo Item 1')
```

**Comment by vasily-v-ryabov** [comment]
Hi @woodsongem, generally it looks like the following:
```python
app.MainWindowTitle.ComboBox.select('Combo Item 1')
```
Taken from pywinauto unit tests for WPF app (`backend="uia"`).

**Comment by airelil** [comment]
@woodsongem, any follow ups ? Can we close the issue ?

**Comment by woodsongem** [comment]
i am using window form. please close this issue. Thanks

**Comment by roarkhabegger** [comment]
Hello! I am also trying to control a windows Form combo box, and I am slightly confused how the above code provided by @vasily-v-ryabov would work. I keep getting an attribute error saying there is no 'select' in the Window Specification class. Below is my code, with the title of the windows form being "Manual Polarimeter Mover [v0.2]" and the "cbMtr" being the name of the combo box
`def movePol(motor,position):
    manPol = app.connect(
        path=r"C:/Users/astrouser/Desktop/ManualPolarimetry-master/ManualPolarimetry-master/ManPol/bin/Release/ManPol.exe")
    manPol["Manual Polarimeter Mover [v0.2]"]["cbMtr"].select(motor)`

**Comment by vasily-v-ryabov** [comment]
Hi @roarkhabegger. No problem. Welcome here. It looks like this attribute error problem is the same as #364. Such an attribute error is raised when the control is found but interpreted as a basic wrapper (not a specific `ComboBoxWrapper`). We have plans to make this error more clear (so keeping #364 open for that).  To check which wrapper is found use the following code:
```python
combo = manPol["Manual Polarimeter Mover [v0.2]"]["cbMtr"].wrapper_object()
print(combo, ) # prints short wrapper info

# optional: to print children ids
manPol["Manual Polarimeter Mover [v0.2]"].print_control_identifiers()
```
If it's `HwndWrapper` probably you need to use `backend="uia"` while doing `connect(...)`. More detailed explanation about multiple backends and other useful things are in the [Getting Started Guide](https://pywinauto.readthedocs.io/en/latest/getting_started.html).

**Comment by roarkhabegger** [comment]
After using that code and reading through pywinauto's documentation a little more, it appears that this line worked:
`pywinauto.controls.win32_controls.ComboBoxWrapper(manPol["Manual Polarimeter Mover [v0.2]"].cbMtr).select(motor)`
Because the new error I got was just that the string I require for the function 'motor' could not be found as a part of the combo box, I think it should work once the windows form is working better.

**Comment by vasily-v-ryabov** [comment]
No, it's because more complicated WindowsForms controls have ugly hex .class_name() property value so that we can't detect control type using Win32 API. That's why I recommend UIAutomation based backend for WinForms. For this backend you will have adequate .control_type() return value. The high level concept is very similar for both backends.
