### ISSUE TITLE
Make IUIA() not a singleton back to resolve potential threading issues

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#394]
This might be a root cause of [the threading issue mentioned on StackOverflow](https://stackoverflow.com/questions/45401017/using-pywinauto-top-window-hangs-when-using-it-with-threads).

**Comment by maxime-viargues-serato** [comment]
Hey I have got the same threading issue. I don't think I can work around it using a single thread. Is there any chance to have a fix for this soon or at least get a hack in the meantime?
Thanks.

**Comment by vasily-v-ryabov** [comment]
Hmm... I'm pretty busy this month. But will try to take some time for that. I think only this issue + NULL COM pointer crash #296 will be included into next bug fix release. Because both issues can't be workarounded. Thanks for follow up.

**Comment by maxime-viargues-serato** [comment]
I have found a way to put it on the main thread but that's not ideal. That will do for now.
Thanks.

**Comment by maxime-viargues-serato** [comment]
Hmm I talked too fast. Well it works on the main application but then I can't run my unit tests which needs to be on a separate thread :(

**Comment by airelil** [comment]
I tried to look into it today. Here several my findings so far.

Comtypes package we use, automatically calls to [CoInitializeEx()](https://github.com/enthought/comtypes/blob/d3fbdd0c2933c9671e80d7407a0320925abc8bc5/comtypes/__init__.py#L165) and [CoUnitialize()](https://github.com/enthought/comtypes/blob/d3fbdd0c2933c9671e80d7407a0320925abc8bc5/comtypes/__init__.py#L175) on the main thread. It means that by default our [IUIA singleton](https://github.com/pywinauto/pywinauto/blob/f0dbeb8a3ae261b63e276818f9f27d96673a0647/pywinauto/uia_defines.py#L62) runs in STA (Single Threaded Appartments). Since the inability to interact with the COM client from other threads - the main thread has to run a special loop with ```PeekMessage()``` and ```DispatchMessages()``` to process messages from other threads sent by UIA. The comtypes initialization can be changed to MTA through  ```sys.coinit_flags``` even without modifying pywinauto sources:
```python
import sys
sys.coinit_flags = 0  # COINIT_MULTITHREADED = 0x0
import pywinauto
```
This will enable access to the COM from different threads. However it comes with the price, the caller has to take care of the thread safety. It works for simple examples like in #416, but more hiccups will quickly pop up with more complicated scenarios. 

Another problem with MTA, I bumped into, is ```RPC_E_CHANGED_MODE``` error. For example, an attempt to run pywinauto unit tests rises WindowsError exception in comtypes init with ```RPC_E_CHANGED_MODE```. Most probably, it's due to another DLL that already set up the main thread mode to STA during its loading. A possible solution would be moving IAUA singleton in a separate thread initialised as MTA, thus allowing access to the COM from different threads (but taking the risks of data access synchronisation)

These are also Microsoft [recommendations](https://msdn.microsoft.com/en-us/library/windows/desktop/ee671692(v=vs.85).aspx) for UI automation threading:
> If your client application is intended to interact with all elements on the desktop, including its own UI, you should make all UI Automation calls from a separate thread. This includes locating elements, for example, by using IUIAutomationTreeWalker or the IUIAutomationElement::FindAll method and using control patterns. This thread should not own any windows, and should be a Component Object Model (COM) Multithreaded Apartment (MTA) model thread (one that initializes COM by calling CoInitializeEx with the COINIT_MULTITHREADED flag.)

 pywinauto satisfies the requirement do not own any windows so, probably, UI Automation calls can be done from any thread. However, from my search in the Internet it's not clear how stable is UI Automation under multi threading.

**Comment by airelil** [comment]
@vasily-v-ryabov, seems that I figured out the ```RPC_E_CHANGED_MODE``` problem in our unit tests: I suspect that pythoncom has been imported implicitly before our code and set up STA mode. Now if I change the imports order in our unit tests we can run them under MTA. Should I create PR to switch on MTA by default or we can stick to STA but users will be required to specify ```sys.coinit_flags = 0``` explicitly before importing pywinauto ?

@maxime-viargues-serato, could you please try running your multi-threading program  with the ```sys.coinit_flags``` as I described in my previous comment ?

**Comment by vasily-v-ryabov** [comment]
@airelil maybe explicit switching to MTA makes sense by default. But I'd suggest to warn user if STA mode was enabled before importing pywinauto. Or maybe some function/property like `threading_mode` makes sense. Calling `sys.coinit_flags = 0` explicitly looks like a hack. Calling `pywinauto.multi_threading_mode = True` is more clear I think.

**Comment by airelil** [comment]
I made some work in my [mta](https://github.com/airelil/pywinauto/commits/mta) branch. These changes switching MTA on by default. So far, looks good, but as usual, got stuck with a couple of failing [unit tests](https://ci.appveyor.com/project/airelil/pywinauto) (not sure yet, if it's related to the change). I also considering to add ```threading.Lock``` to all IUAI calls.

**Comment by maxime-viargues-serato** [comment]
@airelil Yes indeed that fixes the problem to use `sys.coinit_flags = 0`
