### ISSUE TITLE
WindowSpecification class has no 'click' method

### ISSUE THREAD

**Issue by alexgoryachev** [pywinauto/pywinauto#395]
Hi Vasily,

Pywinauto is  able to locate an element and even draw_outline it.  But not able to click on it.  

..  backend="uia, 64 bit, python 2.7 and  3.6 
tdbb = treat_win.child_window(title="TDBB", control_type="TabItem")
tdbb.draw_outline() - works
tdbb.click()               - fails

error message - 
    tdbb.click()
  File "C:\Python36\lib\site-packages\pywinauto\application.py", line 171, in __call__ format(self.criteria[-1]['best_match']))
AttributeError: WindowSpecification class has no 'click' method

So, what's wrong with  my code?

**Comment by airelil** [comment]
Maybe just try to get the wrapper object directly:
```
wrp = tdbb.wrapper_object()
wrp.click()
```

**Comment by vasily-v-ryabov** [comment]
In many cases method `.invoke()` behaves the same way as you would expected from `.click()`. But it may have different meaning. That's why we left it as `.invoke()` for generic case. For `ButtonWrapper` we have `click = invoke`.

I'm planning to implement generic `.click()` raising an exception with recommendation to use `.invoke()` or `.click_input()` instead.

**Comment by alexgoryachev** [comment]
Thank you vasily-v-ryabov and airelil.  Works .click_input() only.
