### ISSUE TITLE
could print Properties.print_control_identifiers() msg?

### ISSUE THREAD

**Issue by jekoie** [pywinauto/pywinauto#400]
```
#coding:utf-8
import sys
from pywinauto import application
reload(sys)
sys.setdefaultencoding('utf-8')

app = application.Application().start('notepad.exe')

app.NotePad.MenuSelect('帮助->关于记事本')
about_dlg = app.window(class_name='#32770')

about_dlg[u'确定'].Click()

print  app.Properties.print_control_identifiers()
```
C:\Python27\python.exe D:/Demo/test.py
Traceback (most recent call last):
  File "D:/Demo/test.py", line 14, in <module>
    print  app.Properties.print_control_identifiers()
  File "C:\Python27\lib\site-packages\pywinauto\application.py", line 584, in print_control_identifiers
    this_ctrl = self.__resolve_control(self.criteria)[-1]
  File "C:\Python27\lib\site-packages\pywinauto\application.py", line 248, in __resolve_control
    raise e.original_exception
pywinauto.findbestmatch.MatchError: Could not find 'Properties' in '[u'\u65e0\u6807\u9898 - \u8bb0\u4e8b\u672cNotepad', u'Notepad', u'\u65e0\u6807\u9898 - \u8bb0\u4e8b\u672c']'

Process finished with exit code 1

**Comment by vasily-v-ryabov** [comment]
Hi @jekoie, why are you trying English name "Properties"? Of course, it's not found for your language. Just use something like `app[u"Name of the dialog in your language"].print_control_identifiers()`. Probably it was from the Getting Started Guide, but it's just an example, you don't have to use the same name `Properties` because every dialog has its own name.
