### ISSUE TITLE
Is there a way to use regex or partial value on "auto_id"?

### ISSUE THREAD

**Issue by jsonpanganiban** [pywinauto/pywinauto#461]
Application I'm testing generates dynamic auto id value, in this case **w19**
```
app = Desktop(backend='uia')
selling_platform_window = app.window(title="SELLING PLATFORM")
selling_platform_window.child_window(auto_id="w19_dep0_input", control_type="Edit")
```
Is there a way to use a partial match, regex, or something like contains for **auto_id** value so I can interact with that control?

**Comment by vasily-v-ryabov** [comment]
Hi @jsonpanganiban currently it's not possible. But we can consider this request for the near future. We're planning to rework search by properties to make it more backend-independent so that `_re` might be used for every property in `child_window(...)` criteria. Thanks for reporting it! Will target to 0.7.0.

**Comment by jsonpanganiban** [comment]
looking forward to that as it would be very useful, thanks!

**Comment by tibile** [comment]
Hi Vasily,
When running your example. I saw a code:
app['PageSetupDlg']['ComboBox1'].select(4)
on https://github.com/vasily-v-ryabov/pywinauto/blob/master/examples/notepad_item.py file.
Could you tell me know how can call the value of control in this code. Because I using spy to inspest C# control, but the control Type or name is not match with you code.
thanks

**Comment by vasily-v-ryabov** [comment]
Hi @tibile this notepad example should work only if some printer installed in the system. In your case structure of the menu is different because no printers installed. You're welcome to re-write this example if you want. But please submit your questions as separate issues if it's not connected with the existing discussion.

**Comment by eltimen** [comment]
I think this is already implemented in atspi branch as `auto_id_re` property. 
Example for `apps\WinForms_samples\ListView_TestApp.exe` sample:
```python
from pywinauto.application import Application

app_full_path = r'ListView_TestApp.exe'
app = Application(backend='uia').connect(path=app_full_path)
dlg = app.window(auto_id_re='Form\\d')
dlg.by(auto_id_re='[lL]istView.+').dump_tree()
```
