### ISSUE TITLE
Reading Spotify App Window

### ISSUE THREAD

**Issue by VictorXLR** [pywinauto/pywinauto#486]
Good Day,

I have been trying to use pywinauto to get the Title of a song from spotify using spy++ and pywinauto and i havent been able to get it to work.
![image](https://user-images.githubusercontent.com/22397950/38570282-dcdaba1c-3cc3-11e8-850c-b61fff6f96a1.png)

```
import pywinauto

wina =pywinauto.findwindows.find_window(handle='000601F2')

print(pywinauto.handleprops.classname('000601F2'))
```
My Goal is to use the handle and get the title of the song playing by reading the GUI of the window. 
Am i missing something here. the module`pywinauto.handleprops.` gives 0 or doesnt return anything for anything passed with that handle.

Is this a problem with spotify or what am i missing here.
Windows 10 Pro 64 Bit

Thank you

**Comment by vasily-v-ryabov** [comment]
Hi @VictorXLR I wouldn't recommend to rely on handle value (it's integer by the way, but you're giving a string) or even Control ID, because they are changing from run to run. Also `handleprops` and `findwindows` are very low level functions so you can use them for your own risk.

The first recommendation is always reading the [Getting Started Guide (section Window Specification)](https://pywinauto.readthedocs.io/en/latest/getting_started.html#window-specification). Hope it helps.
