### ISSUE TITLE
PyWinAuto [UIA Reference]

### ISSUE THREAD

**Issue by Vasanthkvr** [pywinauto/pywinauto#502]
Hi,
Please suggest me which of the following UIA is refered in the PyWinAuto.
1) UIAutomationClient.dll + UIAutomationTypes.dll
2) UIAutomationCore.dll
3) UIAComWrapper.dll

From my understanding PyWinAuto uses the "UIAutomationCore.dll".

**Comment by vasily-v-ryabov** [comment]
Hi @Vasanthkvr you are right. The confirmation is here: [pywinauto/uia_defines.py#L60](https://github.com/pywinauto/pywinauto/blob/master/pywinauto/uia_defines.py#L60).

UIAComWrapper is usually references in C# based tools because it uses native COM interface of the "UIAutomationCore.dll" as well as pywinauto. The only difference is that pywinauto does this using comtypes package.

Many C# tools use  standard .NET wrapper around UI Automation that has its own bugs. So the advantage of UIAComWrapper is pretty the same as in pywinauto's comtypes usage. Other things involve language/library differences for comparison and it's more opinion based.
