### ISSUE TITLE
Static text is considered as dynamic element (former: is_visible returns True for non-visible control)

### ISSUE THREAD

**Issue by kribri** [pywinauto/pywinauto#518]
I have a dialog window with multiple tabs (TabControl). After I switch from tab A to tab B, tabA.Control.is_visible() still returns True, despite the control on tab A is not being visible anymore. The control also doesn't show up in print_control_identifiers().
I would expect False to be returned.

**Comment by vasily-v-ryabov** [comment]
If you re-use the same window specification, the actual search is repeated and another control can be found. You need to remember `tabA.Control.wrapper_object()` to a variable and then re-check `wrapper.is_visible()`. It will guarantee the same control is checked.

**Comment by kribri** [comment]
Thank you for the reply.
I tried switching to tab B _before performing the initial search_, and it still was returning true. 
However, I found out that `tabA.Control.window_text()` was returning text of another element! So for some reason magic attribute name resolves to absolutely different control.
Control on tab A accessed as `dlg.ActivatedStatic`:
   | Static - 'Activated'    (L810, T426, R1143, B454)
   | ['Static7', 'Activated', 'ActivatedStatic']
   | child_window(title="Activated", auto_id="1165", control_type="Text")

Control on tab B, which  `dlg.ActivatedStatic` resolves to:
   | Static - 'lastupdate'    (L1138, T374, R1318, B395)
   | ['lastupdateStatic', 'lastupdate', 'Static10']
   | child_window(title="lastupdate", auto_id="1154", control_type="Text")

If I try to check visibility with `dlg.child_window(title="Activated", auto_id="1165", control_type="Text").is_visible()`, then I get element not found exception, which I guess is an expected behavior. I also get this exception with `is_present()`. I wonder, if there is a way to get False instead of exception?

**Comment by vasily-v-ryabov** [comment]
Method `.exists()` returns `True` or `False` after some timeout (can be passed to the method).

**Comment by kribri** [comment]
Thank you, `exists()` is working as expected.
However, I'm still confused as to why `dlg.ActivatedStatic` resolves to
| Static - 'lastupdate' (L1138, T374, R1318, B395)
| ['lastupdateStatic', 'lastupdate', 'Static10']
| child_window(title="lastupdate", auto_id="1154", control_type="Text")

It looks like the magic name resolution cannot be trusted at all?

**Comment by vasily-v-ryabov** [comment]
Magic name resolution (a.k.a. "best_match" algorithm) is approximate by its nature because it calculates some distance between texts and the closest control (by the disctance) is finally chosen.

But this particular case looks like another problem as `control_type="Text"` is probably recognized as base class `UIAWrapper` with default static member `can_be_label = False`. It means it's considered as dynamic. This is wrong obviously. To fix it `class StaticWrapper(UIAWrapper)` must be created with overridden `can_be_label = True`.

Thanks for reporting this case!

Since the fix is simple, you're free to create pull request and maybe simple unit test for this. I will have enough time for bug fixes in August only.
