### ISSUE TITLE
Allow making WindowSpecification from wrapper

### ISSUE THREAD

**Issue by vasily-v-ryabov** [pywinauto/pywinauto#570]
subj

**Comment by pakal** [comment]
(Dumping here ideas from duplicate ticket #808)

Since one often wants to perform all kinds of operations on descendants of a control, how about adding some kind of WindowSpecification .cache() methods which looks up the currently targeted widget, and uses it directly as "parent" in find_elements() the next time the WindowSpecification is chained to new (sub)criteria?

**Comment by vasily-v-ryabov** [comment]
Caching might be a little bit implicit because next steps don't call `.cache()` method again, but caching still happens. What can make sense is some kind of checking for actual state of the already found top level window (kind of smart caching). Cached state with potential expiration could be more flexible to the situation and it probably could be implemented without explicit call to `.cache()` method.

Generally this concern is similar to what happens with `.too_window()` usage now.

**Comment by pakal** [comment]
Yes caching could be automatic, as long as it resets itself if previously cached widgets have been deleted/recreated in GUI.
