### ISSUE TITLE
Support on MacOs for Qt application

### ISSUE THREAD

**Issue by prathibha-a** [pywinauto/pywinauto#608]
Hi,

I just checked the milestone of PyWinAuto 0.8.0 and understood that you have plans for MacOs.
Does pywinauto on MacOs support Qt based applications?

Just in case if you know:
As per your suggestion in another issue thread i found pyatom/atomac as module to work on MacOs.
but i am struck after the installation due to some issue. And I am yet to get response for the query from team.
Is the team still active? If not could you please suggest me some tool/framework to automate my application on MacOs.

Thanks in advance.

**Comment by vasily-v-ryabov** [comment]
As I know, Apple Accessibility API should work with Qt. Of course, we haven't dealt with cross-OS consistency issues for Qt yet. But Qt should support all desktop OSes accessibility technologies good enough.

@zemtsov-artem is working on macOs support. My estimation for the first release is ~Q4 2019 - Q2 2020.

pyatom/atomac is good for now. Though it works with Python 2.7 only and requires some compilation during installation process. There was an example for iTunes written by one of my students: [AppleID.py](https://github.com/vasily-v-ryabov/ui-automation-course/blob/master/10_Golodyaev/AppleID.py) using pyatom. I think compilation issues can be solved by googling. One more problem with pyatom is flexible timings which are implemented but not working. That's why above example contains hard-coded sleeps.

It's also possible to write automation in AppleScript which doesn't require compilation. It's a little bit unusually, but worked.

**Comment by prathibha-a** [comment]
Thank you for the information Vasily.
I will be waiting for the release of MacOs support of pywinauto.
Meanwhile I will try to start the pyatom automation with the reference of given example.

Thanks again.
