### ISSUE TITLE
In Script execution when application process is killed and app is launched again then all loaded modules refer to earlier memory 

### ISSUE THREAD

**Issue by NeJaiswal** [pywinauto/pywinauto#613]
Hi,
In Script execution when application process is killed and app is launched again then all loaded modules from script refer to earlier memory location, how to re-initialize all the script objects and modules to make script continue execution.

Thanks ,
Neha

**Comment by vasily-v-ryabov** [comment]
Hi @NeJaiswal it depends which objects and how you keep them. Wrapper objects are not reusable anyway because there might be different handle, different AutomationElement pointer etc, though it has the same properties.

WindowSpecification objects created from Application have more potential to be reusable since they are not bound to specific element until actual search is triggered. But current implementation saves process ID of previous app instance in a window spec object while it's created. So calling `app.connect(...)` to the new app instance doesn't update all derived window specifications automatically. To make it possible we need to bind WindowSpecification to Application object instead of hard equipped process id.

The key line making this binding is shown below (`application.py`):
```python
kwargs['process'] = self.process
```
Changing this line to `kwargs['app'] = self` also requires modification in `WindowSpecification.wrapper_object()` method to extract `self.criteria[0]['process'].process` dynamically with updated `.process` attribute of the Application object.

**Comment by vasily-v-ryabov** [comment]
Hi @NeJaiswal the fix is implemented in the branch. Is it possible to test it out and maybe provide more feedback?
It can be installed so:
```
pip uninstall pywinauto
pip install https://github.com/vasily-v-ryabov/pywinauto/archive/app_process_binding.zip
```
