### ISSUE TITLE
list view : unable to click on the checkbox.

### ISSUE THREAD

**Issue by omerbakhtiar** [pywinauto/pywinauto#622]
![blog](https://user-images.githubusercontent.com/19408738/49568742-b2132100-f953-11e8-80f0-5a26c564f81a.png)
we have tried below code but it select the text but not the checkbox
     dialog_compound= context.ftk_app[u'Compound File Expansion Options']
        dialog_compound.set_focus()
        dialog_compound['Clear All'].click()
        time.sleep(10)
        files_list_view = dialog_compound.child_window( control_id=1066 )
        files_list_view.select(1)
        time.sleep(4)
if i try  below line 
files_list_view.select(1).check_by_click()
i get the error .
![identifiers](https://user-images.githubusercontent.com/19408738/49568875-19c96c00-f954-11e8-9160-f44409163426.png)

**Comment by omerbakhtiar** [comment]
oh i figured out the solution
files_list_view.select(0).Check()

**Comment by vasily-v-ryabov** [comment]
Hi @omerbakhtiar glad you've found the solution. Just a few comments. I wouldn't recommend using `control_id` property in search criteria because it can change from run to run or after changing window layout even if the target control wasn't changed. Usually `auto_id` or `title` in combination with `control_type` are the best choice.

Hard-coded `time.sleep` calls are not reliable and slow. pywinauto can solve timing problems by using method `.wait('enabled', timeout=10)` for window specification where 10 seconds is maximum time to wait but it may be finished earlier right after the window is shown. So it can speed your test up and make it more reliable.

See [Waiting for Long Operations](https://pywinauto.readthedocs.io/en/latest/wait_long_operations.html) for more details.
