### ISSUE TITLE
Hide/Filter element

### ISSUE THREAD

**Issue by xor0x** [pywinauto/pywinauto#682]
Hello. How i can hide or filter specific element.
Example: i wanna hide table with 600 rows because i wanna get only control_type "Edit".
Where i use print_control_identifiers() it is print all child_window including Table with 600 rows it is take a long time for print.

**Comment by xor0x** [comment]
Please help me

**Comment by airelil** [comment]
@xor0x , ```print_control_identifiers``` doesn't have built-in filtering functionality as it supposed to dump all visible controls. The only option for you is to play with ```depth``` parameter, if it can help. Otherwise, you may opt out to iterate manually through window descendants. Notice that ```descendants``` methods for both backends (UIA and win32) accept ```control_type``` and ```class_name``` filtering options. Here a basic example for win32 backend.
```python
import pywinauto.application
app = pywinauto.application.Application()
app.start(cmd_line='notepad.exe')
top_win = app.top_window()
for w in top_win.descendants(class_name='Edit'):
    print(str(w))
```

**Comment by xor0x** [comment]
Thnx
