### ISSUE TITLE
AttributError:mould 'comtypes.gen.UIAutomationClient' has no attribute 'CUIAutomation'

### ISSUE THREAD

**Issue by wwling2001** [pywinauto/pywinauto#751]
## Expected Behavior
we made a python toy tool using pywinauto and we pack the source to a exe package by pyinstaller. When we execute the exe tool if we login the windows system and click the exe tool, it works well. 

## Actual Behavior
But it failed when we deliveried the package to another windows and call it by paramiko package through SSH. we get the fellow error messages。
![image](https://user-images.githubusercontent.com/4679457/58924829-f010c680-8777-11e9-9451-4c514ee1f807.png)

## Specifications

  - Pywinauto version: 0.6.6
  - Python version and bitness: 3.6.5
  - Platform and OS: windows server 2012

**Comment by vasily-v-ryabov** [comment]
It looks like `comtypes` cache is not generated properly on remote machine. Maybe the reason is too low write permissions by SSH. Yes, Python wrapper for `UIAutomationCore.dll` is generated dynamically at first run.

Anyway GUI automation won't work by SSH (not only pywinauto, but any other library) because SSH server doesn't forward any GUI info to SSH client. See [Remote Execution Guide](https://pywinauto.readthedocs.io/en/latest/remote_execution.html) on how to run GUI automation script remotely right way.

**Comment by rchai** [comment]
In case anyone else bumps into this horror of a bug - you need to clean the comtypes_cache, but on the target machine - NOT on the machine where you created the .exe
Note that the comtypes_cache can be in different places. I found it under C:\Users\Administrator\AppData\Local\Temp\comtypes_cache
But it can also be in Roaming instead of Local, or elsewhere. Run a search for the comtypes_Cache directory and you'll find it.
Good luck

**Comment by vasily-v-ryabov** [comment]
Another option is using hidden-import for module generated by comtypes. See https://github.com/enthought/comtypes/issues/340

**Comment by jakub-stefaniak** [comment]
@rchai solution saved me. Thank you 🙏
