### ISSUE TITLE
Automation of elements on WPF using pywinauto

### ISSUE THREAD

**Issue by marathe-vidya** [pywinauto/pywinauto#754]
```
`from pywinauto.application import Application

app = Application().connect( title= "Book")
bookWin = app[u'WindowsForms10.Window.8.app.0.aec740_r9_ad1']
bookWin .SetFocus()

closeButton = bookWin [u'Close']
closeButton.click()`
```
I had written this code snippet, it looks correct but I could not access the Close button.

I get the following error (ElementNotFoundError):
 raise e.original_exception
pywinauto.findwindows.ElementNotFoundError: {'best_match': u'Close', 'top_level_only': False, 'parent': <win32_element_info.HwndElementInfo - 'Book', HwndWrapper[MaintenanceTool.exe;;f521f66d-ecad-4107-be40-049c826c6ee2], 9637874>, 'backend': u'win32'}

  - Pywinauto version:      pywinauto - 0.6.5
  - Platform and OS:         Windows 10

Also, I am not able to get the list of elements on the WPF form using automation tools.
I tried to find a solution on internet and found out we need to assign Automation ID for all the elements in order to access them? Is there any other way to access (if automation ID is not provided)??

**Comment by airelil** [comment]
Uour code uses the default Win32 backend. For WPF applications you'd better use UIA backend.

**Comment by sachinpatole** [comment]
> Uour code uses the default Win32 backend. For WPF applications you'd better use UIA backend.

@airelil  - what if  automation ID are not provided??? Will use of UIA backend solve the problem? For me it did not...

I am facing same issue. I have a WPF applications (automation ID are NOT provided), could not access window GUI objects from SWAPY. 

Is there any other way to do automation (in Python only) of WPF applications without automation IDs???

**Comment by marathe-vidya** [comment]
> Uour code uses the default Win32 backend. For WPF applications you'd better use UIA backend.

@airelil Tried using 'uia' but still have the same issue..
What if my main app happens to be C# or some other technology and one particular window is WPF ? Should I still use backend = 'uia' ??

**Comment by airelil** [comment]
I definitely can't speak for all the applications, but usually WPF and C# based programs have decent UIA integration, and I believe that "UIA" backend should be your first choice. Notice that SWAPY is not supported for the last couple of years, so the GUI elements visible in SWAPY are only the elements that accessible through original "win32" back end.  Instead of SWAPY I would suggest using "Inspect.exe" utility, but it's important to make sure to run Inspect.exe in "UIA mode". Basically, if the elements are visible in Inspect.exe they should be accessible thorough pywinauto uia backend too. To make your way through the GUI hierarchy try to use ```print_control_identifiers```. The output of the method should provide you with clues about controls and their names visible to pywinauto.

@marathe-vidya , since you have a problem accessing 'Close' element you may try discover it with above mentioned ```print_control_identifiers```:
```python
from pywinauto.application import Application

app = Application(backend='uia').connect(title= "Book")
bookWin = app[u'WindowsForms10.Window.8.app.0.aec740_r9_ad1']
bookWin.SetFocus()
book.print_control_identifiers(depth=3)
``` 
Notice, the ```depth``` parameter you may want to play with it, but remember that going down through complicated control hierarchy can be time consuming operation.

PS: also don't forget to go through some docs: https://pywinauto.readthedocs.io/en/latest/getting_started.html?highlight=inspect.exe

**Comment by sachinpatole** [comment]
@airelil Thanks its worked !!!

**Comment by vasily-v-ryabov** [comment]
@sachinpatole @marathe-vidya great. Can we close this issue then? :)

**Comment by sachinpatole** [comment]
Yes, Thanks for awesome work!!!
