### ISSUE TITLE
Is there a way to reconnect with the application?

### ISSUE THREAD

**Issue by strange-dragon** [pywinauto/pywinauto#764]
While testing an application with pywinatuo,  the application lost connection to pywinatuo. And I couldn't use connect() to connect my application. It showed it couldn't find the application. If  I kill the progress and reopen my application, pywinatuo can find that again.
So I wonder if there is a way to reconnect with the application? Or there are any way  to avoid losing connection ?
Thank you anyway.

**Comment by airelil** [comment]
@strange-dragon, you didn't provide much info. What's exact error message you get?

Generally, pywiauto tracks the application by app's process id. The PID is resolved on running connect or start methods. So you might want to check if tge pricess is still active and has tge sane PID. In case the process is not respinsive or doesn't have any visible window, you also might get the error.

**Comment by vasily-v-ryabov** [comment]
The question is not clear. How do you imagine that "application lost connection"? :) Application doesn't know about pywinauto. :)

Sometimes you may face the situation when application spawns another process that contains some windows. pywinauto doesn't detect such spawned processes automatically. So you have to connect to this new process by title, for example. Just learn parameters of method `.connect(...)` in more details.

Also it's possible to use class `Desktop` instead of `Application` so that you don't stick to particular process. It could look like this:
```python
from pywinauto import Desktop
desktop = Desktop(backend="uia")
main_window = desktop.window(title="Main Window Title")
main_window.wait('visible', timeout=10)
```

**Comment by vasily-v-ryabov** [comment]
The feature for auto detection of spawned processes is tracked here: #593.
