### ISSUE TITLE
Clicking button not working

### ISSUE THREAD

**Issue by jjbright** [pywinauto/pywinauto#819]
I wanted to click the ### **Dashboard** button.

I navigate thru child_window=> 'Toolbar Container' => 'Main' => 'Dashboard' [dot] click_input()

but, there is **_'DashboardGroupBox'_**, how do I pass thru this?

```
TabItem - 'Toolbar Container'    (L0, T0, R0, B0)
   |    |    |    | ['TabItem2', 'Toolbar Container', 'Toolbar ContainerTabItem']
   |    |    |    | **child_window(title="Toolbar Container", auto_id="Toolbar Container", control_type="TabItem")**
   |    |    |    |    | 
   |    |    |    |    | GroupBox - ''    (L19, T42, R1013, B72)
   |    |    |    |    | **_['GroupBox2', 'DashboardGroupBox', 'DashboardGroupBox0', 'DashboardGroupBox1']_**
   |    |    |    |    |    | 
   |    |    |    |    |    | Toolbar - 'Main'    (L19, T42, R578, B72)
   |    |    |    |    |    | ['MainToolbar', 'Main', 'Toolbar', 'Toolbar0', 'Toolbar1']
   |    |    |    |    |    | **child_window(title="Main", auto_id="Main", control_type="ToolBar")**
   |    |    |    |    |    |    | 
   |    |    |    |    |    |    | Button - ''    (L0, T0, R0, B0)
   |    |    |    |    |    |    | ['', 'Button', '0', '1', 'Button0', 'Button1']
   |    |    |    |    |    |    | **child_window(auto_id="Dashboard", control_type="Button")**
```
## Specifications

  - Pywinauto version: 0.6.7
  - Python version and bitness: 3.7 64 bit
  - Platform and OS: Windows 10 64 bit

@funkyHat @pakal @batterseapower @vasily-v-ryabov   Please help

**Comment by jjbright** [comment]
Here is the code now it worked, after trying a few combinations.  The BOLD line made it to work.

`_a1_ = mwa.child_window(title="Toolbar Panel", auto_id="ToolbarPanel", control_type="Pane")
        _a2_ = _a1_.child_window(title="Toolbar Container", auto_id="Toolbar Container", control_type="TabItem")
        **_b1_ = _a2_.child_window(best_match=u'DashboardGroupBox')**
        _a3_ = _a1_.child_window(title="Main", auto_id="Main", control_type="ToolBar")
        _a4_ = _a3_.child_window(auto_id="Dashboard", control_type="Button").click_input()`

**Comment by pakal** [comment]
I think you don't need so many variables, child_window() actually browses all descendants of the Application() or Desktop(), so just filtering with child_window(auto_id="Dashboard", control_type="Button") should target the proper button.

PS : in some cases you might want to use .toggle()  (or .click(), it depends on the wrapper class which ends up being used) instead of .click_input(), if in some cases the control is not readily available (offscreen, or hidden in a scroll panel bottom...) ; but from my experience click_input() simulates mouse interaction more faithfully, in cases where other methods don't trigger all GUI callbacks.

**Comment by jjbright** [comment]
Done
