### ISSUE TITLE
UI Automation tools ratings, add http://robotjs.io/

### ISSUE THREAD

**Issue by zhoujin7** [pywinauto/pywinauto#857]
https://github.com/pywinauto/pywinauto/wiki/UI-Automation-tools-ratings
add http://robotjs.io/
https://github.com/octalmage/robotjs

**Comment by vasily-v-ryabov** [comment]
OK, I've added it to the rating. The only doubt I have that NodeJS apps work inside browser. So it's not a desktop app, but a web app. Our rating doesn't contain Selenium and other web-UI testing tools because this is completely different technology. But RobotJS uses desktop OS functions inside. So it's fair to add it to our rating despite it looks crazy to me personally.

In my mind Web-UI should be automated by Web-UI automation tools. Some combination with desktop based tools makes sense to handle popup windows, file open/save dialogs etc. Not sure some mixed tool shows something in the rating.
