### ISSUE TITLE
how to get a Window Specification when I have a BaseWrapper object

### ISSUE THREAD

**Issue by zhiming429438709** [pywinauto/pywinauto#967]

**Comment by zhiming429438709** [comment]
quesion

**Comment by vasily-v-ryabov** [comment]
Currently there is no way to get back to WindowSpecification. We're planning to implement creating new child WindowSpecification from current wrapper as a parent. Keeping already used WindowSpecification inside wrapper object doesn't make much sense because you already can keep it in a variable if you need.
