### ISSUE TITLE
An error occurred using PyInstaller to generate an exe file

### ISSUE THREAD

**Issue by 19946009938** [pywinauto/pywinauto#969]
An error occurred using PyInstaller to generate an exe file .Has anyone had a problem with this code?

## Specifications

  - Pywinauto version: 0.6.3
  - Python version and bitness: 3.6
  - Platform and OS: windows

![image](https://user-images.githubusercontent.com/56359932/89782750-70834200-db48-11ea-898e-2adfb352563a.png)

**Comment by vasily-v-ryabov** [comment]
It doesn't look like pywinauto issue. Can you provide PyInstaller recipe or setup.py code?

**Comment by 19946009938** [comment]
> It doesn't look like pywinauto issue. Can you provide PyInstaller recipe or setup.py code?

from pywinauto.application import Application

Just one line of code
I don't understand

**Comment by vasily-v-ryabov** [comment]
This is about how to include 3rd-party packages (like pywinauto) into your executable. You need additional efforts writing PyInstaller recipe. After the executable works on local machine, you may face another problem: your exe won't work on other machine because there is no comtypes cached .py files. This problem is comtypes related, but I plan to workaround or fix it somehow in the future.

Example of PyInstaller .spec file: https://github.com/pywinauto/py_inspect/blob/kivy/PyInspect.spec

**Comment by 19946009938** [comment]
done

**Comment by GoelPri** [comment]
hey, has anyone resolved this?
